//! dapz Compression Benchmark Report
//!
//! Loads JSON fixture files from `fixtures/bench/`, runs all interceptors,
//! and outputs a Markdown report measuring compact JSON and TOON token savings.
//!
//! Run: just gen-bench / just bench-report

use std::path::Path;

use serde_json::Value;
use tiktoken_rs::cl100k_base;

use dapz::codec::json_rpc::DapMessage;
use dapz::codec::toon::value_to_toon;
use dapz::interceptors::Interceptor;
use dapz::interceptors::capping::CappingInterceptor;
use dapz::interceptors::evaluate::EvaluateCompressor;
use dapz::interceptors::exception::ExceptionInfoCompressor;
use dapz::interceptors::output::OutputCompressor;
use dapz::interceptors::scopes::ScopesCompressor;
use dapz::interceptors::stacktrace::StackTraceCompressor;
use dapz::interceptors::variables::VariablesCompressor;
use dapz::proxy::Direction;

const VERSION: &str = env!("CARGO_PKG_VERSION");

fn get_today() -> String {
    let output = std::process::Command::new("date").arg("+%Y-%m-%d").output();
    match output {
        Ok(o) => String::from_utf8_lossy(&o.stdout).trim().to_string(),
        Err(_) => "unknown".to_string(),
    }
}

struct FixtureCase {
    name: String,
    interceptor: String,
    message: DapMessage,
}

fn load_fixtures(path: &str) -> Vec<FixtureCase> {
    let content = std::fs::read_to_string(path).unwrap_or_else(|e| {
        eprintln!("Error reading {}: {}", path, e);
        std::process::exit(1);
    });
    let cases: Vec<Value> = serde_json::from_str(&content).unwrap_or_else(|e| {
        eprintln!("Error parsing {}: {}", path, e);
        std::process::exit(1);
    });
    cases
        .into_iter()
        .map(|c| {
            let msg: DapMessage =
                serde_json::from_value(c["message"].clone()).unwrap_or_else(|e| {
                    eprintln!("Error parsing message in {}: {}", path, e);
                    std::process::exit(1);
                });
            FixtureCase {
                name: c["name"].as_str().unwrap().to_string(),
                interceptor: c["interceptor"].as_str().unwrap().to_string(),
                message: msg,
            }
        })
        .collect()
}

fn make_interceptor(name: &str) -> Option<Box<dyn Interceptor>> {
    match name {
        "output_compressor" => Some(Box::new(OutputCompressor)),
        "evaluate_compressor" => Some(Box::new(EvaluateCompressor::new(500))),
        "variables_compressor" => Some(Box::new(VariablesCompressor::new(120))),
        "stacktrace_compressor" => Some(Box::new(StackTraceCompressor)),
        "scopes_compressor" => Some(Box::new(ScopesCompressor)),
        "exception_info_compressor" => Some(Box::new(ExceptionInfoCompressor::new(800))),
        "capping_interceptor" => Some(Box::new(CappingInterceptor::new(5, 5, 500))),
        _ => None,
    }
}

struct BenchResult {
    orig_tokens: usize,
    comp_tokens: usize,
    toon_tokens: usize,
}

async fn bench_case(bpe: &tiktoken_rs::CoreBPE, case: &FixtureCase) -> Option<BenchResult> {
    let orig_json = serde_json::to_string(&case.message).unwrap();
    let orig_tokens = bpe.encode_with_special_tokens(&orig_json).len();

    let compressor = make_interceptor(&case.interceptor)?;
    let result = match compressor
        .intercept(case.message.clone(), Direction::ServerToClient)
        .await
    {
        Ok(Some(v)) => v,
        Ok(None) | Err(_) => return None,
    };

    let comp_json = serde_json::to_string(&result).unwrap();
    let comp_tokens = bpe.encode_with_special_tokens(&comp_json).len();

    // MCP/SDK path: TOON from response body (or whole message if no body).
    let toon_value = result
        .body
        .clone()
        .unwrap_or_else(|| serde_json::to_value(&result).unwrap_or(Value::Null));
    let toon_tokens = match value_to_toon(&toon_value) {
        Ok(text) => bpe.encode_with_special_tokens(&text).len(),
        Err(_) => comp_tokens,
    };

    Some(BenchResult {
        orig_tokens,
        comp_tokens,
        toon_tokens,
    })
}

fn pct(a: usize, b: usize) -> f64 {
    if a == 0 {
        0.0
    } else {
        (a as f64 - b as f64) / a as f64 * 100.0
    }
}

const COMPRESSOR_CN: &[(&str, &str)] = &[
    ("output.json", "OutputCompressor"),
    ("evaluate.json", "EvaluateCompressor"),
    ("variables.json", "VariablesCompressor"),
    ("stacktrace.json", "StackTraceCompressor"),
    ("scopes.json", "ScopesCompressor"),
    ("exception.json", "ExceptionInfoCompressor"),
    ("capping.json", "CappingInterceptor"),
];

#[tokio::main]
async fn main() {
    let bpe = cl100k_base().expect("Failed to initialize tiktoken");
    let fixture_dir = Path::new("fixtures/bench");

    println!(
        "<!-- AUTO-GENERATED by examples/bench-report.rs. Do not edit manually. Run: just gen-bench -->"
    );
    println!();
    println!("# dapz 压缩基准测试报告\n");
    println!("**版本**: v{}\n", VERSION);
    println!("**日期**: {}  \n", get_today());
    println!(
        "测量标准：原始/紧凑 = 整条 DAP JSON（`cl100k_base`）；TOON = 压缩后 `body` 经 `value_to_toon`（对齐 MCP/SDK 出口）。\n"
    );
    println!("| 压缩器 | 场景 | 原始 (T) | 紧凑 (T) | TOON (T) | Δ% 紧凑 | Δ% TOON |");
    println!("|----------|------|----------|----------|----------|---------|---------|");

    let mut all_results: Vec<(String, Vec<BenchResult>)> = Vec::new();

    for (filename, eng_name) in COMPRESSOR_CN {
        let path = fixture_dir.join(filename);
        let cases = load_fixtures(&path.to_string_lossy());

        let mut results: Vec<BenchResult> = Vec::new();

        for case in &cases {
            match bench_case(&bpe, case).await {
                Some(result) => {
                    println!(
                        "| {} | {} | {} | {} | {} | {:.1}% | {:.1}% |",
                        eng_name,
                        case.name,
                        result.orig_tokens,
                        result.comp_tokens,
                        result.toon_tokens,
                        pct(result.orig_tokens, result.comp_tokens),
                        pct(result.orig_tokens, result.toon_tokens),
                    );
                    results.push(result);
                }
                None => {
                    println!("| {} | {} | — | — | — | — | — |", eng_name, case.name);
                }
            }
        }

        if !results.is_empty() {
            all_results.push((eng_name.to_string(), results));
        }
    }

    println!();
    println!("## 总结\n");
    println!("| 压缩器 | 场景数 | 原始 (T) | 紧凑 (T) | TOON (T) | Δ% 紧凑 | Δ% TOON |");
    println!("|----------|--------|----------|----------|----------|---------|---------|");

    let mut grand_orig: usize = 0;
    let mut grand_comp: usize = 0;
    let mut grand_toon: usize = 0;

    for (name, results) in &all_results {
        let total_orig: usize = results.iter().map(|r| r.orig_tokens).sum();
        let total_comp: usize = results.iter().map(|r| r.comp_tokens).sum();
        let total_toon: usize = results.iter().map(|r| r.toon_tokens).sum();
        grand_orig += total_orig;
        grand_comp += total_comp;
        grand_toon += total_toon;
        println!(
            "| {} | {} | {} | {} | {} | {:.1}% | {:.1}% |",
            name,
            results.len(),
            total_orig,
            total_comp,
            total_toon,
            pct(total_orig, total_comp),
            pct(total_orig, total_toon),
        );
    }

    if !all_results.is_empty() {
        println!(
            "| **总体** | **{}** | **{}** | **{}** | **{}** | **{:.1}%** | **{:.1}%** |",
            all_results.iter().map(|(_, r)| r.len()).sum::<usize>(),
            grand_orig,
            grand_comp,
            grand_toon,
            pct(grand_orig, grand_comp),
            pct(grand_orig, grand_toon),
        );
    }
    println!();
}
